# Generated by Django 3.0.8 on 2022-01-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_buyer',
            new_name='is_agent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_supplier',
            new_name='is_showroom',
        ),
    ]
