# Generated by Django 3.0.8 on 2022-01-25 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220125_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_agent',
            new_name='is_buyer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_showroom',
            new_name='is_supplier',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
