# Generated by Django 3.0.8 on 2021-12-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('taluka', models.CharField(max_length=120, unique=True)),
                ('district', models.CharField(max_length=120, unique=True)),
                ('mobile_number', models.IntegerField()),
            ],
        ),
    ]
