# Generated by Django 3.0.8 on 2021-12-29 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='district',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='agent',
            name='taluka',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='goods_company',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sfsf', to='store.company'),
        ),
    ]
