# Generated by Django 3.0.8 on 2021-12-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211230_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_company',
            name='goods_company_name',
            field=models.CharField(default='sdsd', max_length=120),
            preserve_default=False,
        ),
    ]
