# Generated by Django 3.0.8 on 2021-12-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_goods_company_goods_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_goods',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
