# Generated by Django 3.0.8 on 2021-12-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211230_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_goods',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
