# Generated by Django 3.0.8 on 2022-01-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211230_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_goods',
            name='total_bag',
        ),
        migrations.RemoveField(
            model_name='company_goods',
            name='total_pck',
        ),
    ]
