# Generated by Django 3.0.8 on 2022-01-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20220110_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='place',
            field=models.CharField(default='abc', max_length=120),
            preserve_default=False,
        ),
    ]
