# Generated by Django 3.0.8 on 2022-01-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20220112_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.CharField(default='akola', max_length=120),
            preserve_default=False,
        ),
    ]
