# Generated by Django 3.0.8 on 2022-01-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_agent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ddfdf', to='store.company'),
            preserve_default=False,
        ),
    ]
