# Generated by Django 3.0.8 on 2022-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_agent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_goods',
            name='bag_size',
            field=models.CharField(max_length=120),
        ),
    ]
