# Generated by Django 3.0.8 on 2022-01-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20220115_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_goods',
            name='pck_size',
            field=models.CharField(max_length=120),
        ),
    ]
