# Generated by Django 3.0.8 on 2022-02-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20220222_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
