# Generated by Django 4.1.5 on 2023-02-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_remove_outward_agent_delete_supply_return'),
        ('store', '0025_godown'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='agent',
            name='company',
        ),
        migrations.DeleteModel(
            name='transport',
        ),
        migrations.RemoveField(
            model_name='company_goods',
            name='company',
        ),
        migrations.RemoveField(
            model_name='goods_company',
            name='company_goods',
        ),
        migrations.RemoveField(
            model_name='goods_company',
            name='company_name',
        ),
        migrations.DeleteModel(
            name='agent',
        ),
    ]
