# Generated by Django 4.1.5 on 2023-03-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_remove_inward_company_remove_outward_company_and_more'),
        ('store', '0026_alter_agent_unique_together_remove_agent_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company',
        ),
    ]
