# Generated by Django 4.1.5 on 2023-03-26 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_company',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.company_goods'),
            preserve_default=False,
        ),
    ]
