# Generated by Django 4.1.5 on 2023-03-28 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_goods_company_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_goods',
            name='godown',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.godown'),
            preserve_default=False,
        ),
    ]
