# Generated by Django 4.1.5 on 2023-04-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_company_goods_godown'),
    ]

    operations = [
        migrations.CreateModel(
            name='dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('mobile_no', models.IntegerField()),
            ],
        ),
    ]
