# Generated by Django 3.0.8 on 2021-12-27 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('taluka', models.CharField(max_length=120, unique=True)),
                ('district', models.CharField(max_length=120, unique=True)),
                ('mobile_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='outward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bags', models.IntegerField()),
                ('DC_number', models.IntegerField()),
                ('DC_date', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='df', to='transactions.agent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fgv', to='store.company')),
                ('company_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fd', to='store.company_goods')),
                ('goods_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvg', to='store.goods_company')),
            ],
        ),
        migrations.CreateModel(
            name='inward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bags', models.IntegerField()),
                ('DC_number', models.IntegerField()),
                ('DC_date', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdv', to='transactions.agent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdwe', to='store.company')),
                ('company_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfgv', to='store.company_goods')),
                ('goods_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xvc', to='store.goods_company')),
            ],
        ),
    ]
