# Generated by Django 3.0.8 on 2021-12-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_agent'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdv', to='store.agent'),
        ),
        migrations.AlterField(
            model_name='outward',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='df', to='store.agent'),
        ),
        migrations.DeleteModel(
            name='agent',
        ),
    ]
