# Generated by Django 3.0.8 on 2022-01-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20211229_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='DC_number',
            field=models.CharField(max_length=566),
        ),
    ]
