# Generated by Django 3.0.8 on 2022-01-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20220104_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outward',
            name='DC_number',
            field=models.CharField(max_length=566),
        ),
    ]
