# Generated by Django 3.0.8 on 2022-01-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211230_1314'),
        ('transactions', '0004_auto_20220104_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bags', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsdsdgv', to='store.company')),
                ('company_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsdsdd', to='store.company_goods')),
                ('goods_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csdsvg', to='store.goods_company')),
            ],
        ),
    ]
