# Generated by Django 3.0.8 on 2022-01-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20220104_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_pck',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
