# Generated by Django 3.0.8 on 2022-01-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_stock_total_pck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='total_pck',
        ),
    ]
