# Generated by Django 3.0.8 on 2022-01-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_stock_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='agent',
        ),
    ]
