# Generated by Django 3.0.8 on 2022-01-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211230_1314'),
        ('transactions', '0010_remove_stock_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='agent',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='sdsd', to='store.agent'),
            preserve_default=False,
        ),
    ]
