# Generated by Django 3.0.8 on 2022-01-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20220112_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='DC_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='outward',
            name='DC_date',
            field=models.DateTimeField(),
        ),
    ]
