# Generated by Django 3.0.8 on 2022-01-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20220113_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply_return',
            name='DC_date',
            field=models.DateTimeField(),
        ),
    ]
