# Generated by Django 3.0.8 on 2022-02-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20220113_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inward',
            options={'ordering': ['company', 'company_goods', 'goods_company', 'agent']},
        ),
        migrations.AlterModelOptions(
            name='outward',
            options={'ordering': ['company', 'company_goods', 'goods_company', 'agent']},
        ),
    ]
