# Generated by Django 3.0.8 on 2022-02-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20220222_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inward',
            options={},
        ),
        migrations.AlterModelOptions(
            name='outward',
            options={},
        ),
        migrations.AlterField(
            model_name='outward',
            name='DC_number',
            field=models.IntegerField(),
        ),
    ]
