# Generated by Django 3.0.8 on 2022-02-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20220224_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='DC_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='inward',
            name='bags',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='outward',
            name='DC_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='outward',
            name='bags',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_bag',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='supply_return',
            name='bags',
            field=models.BigIntegerField(),
        ),
    ]
