# Generated by Django 4.1.5 on 2023-02-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_godown'),
        ('transactions', '0024_auto_20221225_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outward',
            old_name='bill_no',
            new_name='gate_pass_no',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='bill_no',
        ),
        migrations.AddField(
            model_name='inward',
            name='godown',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sdwe', to='store.godown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outward',
            name='gate_pass_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outward',
            name='gate_pass_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outward',
            name='godown',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fgv', to='store.godown'),
            preserve_default=False,
        ),
    ]
