# Generated by Django 4.1.5 on 2023-02-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_rename_bill_no_outward_gate_pass_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='DC_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='outward',
            name='DC_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='supply_return',
            name='DC_date',
            field=models.DateField(),
        ),
    ]
