# Generated by Django 4.1.5 on 2023-02-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_alter_inward_dc_date_alter_outward_dc_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply_return',
            name='agent',
        ),
        migrations.AddField(
            model_name='supply_return',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
