# Generated by Django 4.1.5 on 2023-02-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_remove_supply_return_agent_supply_return_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outward',
            name='gate_pass_material',
        ),
        migrations.RemoveField(
            model_name='supply_return',
            name='name',
        ),
        migrations.AlterField(
            model_name='outward',
            name='gate_pass_no',
            field=models.BigIntegerField(default=1111),
        ),
    ]
