# Generated by Django 4.1.5 on 2023-02-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_remove_outward_gate_pass_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward',
            name='agent',
        ),
        migrations.AlterField(
            model_name='outward',
            name='gate_pass_no',
            field=models.BigIntegerField(blank=True, default=1111, null=True),
        ),
    ]
