# Generated by Django 4.1.5 on 2023-02-13 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_remove_inward_agent_alter_outward_gate_pass_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward',
            name='LR_number',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='freight',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='LR_number',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='freight',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='transport',
        ),
    ]
