# Generated by Django 4.1.5 on 2023-02-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_remove_inward_lr_number_remove_inward_freight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward',
            name='employee_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outward',
            name='employee_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
