# Generated by Django 4.1.5 on 2023-02-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_godown'),
        ('transactions', '0031_inward_employee_name_outward_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='godown',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sfwwfddfds', to='store.godown'),
            preserve_default=False,
        ),
    ]
