# Generated by Django 4.1.5 on 2023-02-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_stock_godown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outward',
            name='agent',
        ),
        migrations.DeleteModel(
            name='supply_return',
        ),
    ]
