# Generated by Django 4.1.5 on 2023-02-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_remove_outward_agent_delete_supply_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='DC_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='outward',
            name='DC_number',
            field=models.CharField(max_length=50),
        ),
    ]
