# Generated by Django 4.1.5 on 2023-02-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_alter_inward_dc_number_alter_outward_dc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
