# Generated by Django 4.1.5 on 2023-03-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_remove_inward_buyer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward',
            name='company',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='company',
        ),
    ]
