# Generated by Django 4.1.5 on 2023-04-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_remove_inward_company_remove_outward_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outward',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outward',
            name='name_of_buyer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
