# Generated by Django 4.1.5 on 2023-04-14 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_dealer'),
        ('transactions', '0039_remove_outward_name_of_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='outward',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtrtrtrg', to='store.dealer'),
        ),
    ]
